services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_visa
    restart: always
    ports:
      - "6333:6333" # API REST e Dashboard Web
      - "6334:6334" # Interface gRPC
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__ENABLE_STATIC_CONTENT=true